Vagrant.configure("2") do |config|
  config.vm.box_download_insecure=true

### DB MySQL ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "ubuntu/jammy64"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provision "shell", path: "mysql.sh"
  end
end
