Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.box_download_insecure = true

### DB MariaDB ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
    db01.vm.provision "shell", path: "mysql.sh"
  end
  
### Apache Webserver ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "ubuntu/focal64"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.16"
    app01.vm.provision "shell", path: "apache.sh"
  end
end

